'use client';

import { useState, useEffect } from 'react';
import { Flame, Copy, Check, X, Share2 } from 'lucide-react';

export default function App() {
  const [idea, setIdea] = useState('');
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [wallIdeas, setWallIdeas] = useState([]);
  const [selectedIdea, setSelectedIdea] = useState(null);
  const [shareUrl, setShareUrl] = useState('');

  useEffect(() => {
    fetchWallIdeas();
  }, []);

  const fetchWallIdeas = async () => {
    try {
      const res = await fetch('/api/ideas?limit=20');
      const data = await res.json();
      setWallIdeas(data.ideas || []);
    } catch (err) {
      console.error('Failed to fetch ideas:', err);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setResponse(null);
    setShareUrl('');

    if (idea.length < 50) {
      setError("That's not an idea, that's a tweet. Give us more details!");
      return;
    }

    if (idea.length > 2000) {
      setError("Whoa there - keep it under 2000 characters. We're roasting, not reading a novel.");
      return;
    }

    setLoading(true);

    try {
      const res = await fetch('/api/roast', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ idea }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || 'Failed to roast your idea');
        setLoading(false);
        return;
      }

      setResponse(data);
      setShareUrl(`${window.location.origin}/roast/${data.id}`);
      fetchWallIdeas(); // Refresh wall
    } catch (err) {
      setError("Oops! Our AI is taking a break. Try again in a moment.");
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (!response) return;

    const text = `YOUR IDEA:\n${response.idea}\n\n🔥 THE ROAST\n${response.roast}\n\n💡 10 PROBLEMS YOU'LL FACE\n\n${response.problems
      .map((p, i) => `Problem #${i + 1}: ${p.problem}\nSolution: ${p.solution}`)
      .join('\n\n')}\n\n---\nGenerated by RoastMyIdea.com`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const shareRoast = () => {
    if (!shareUrl) return;
    navigator.clipboard.writeText(shareUrl);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  };

  const openIdeaModal = async (ideaId) => {
    try {
      const res = await fetch(`/api/roast/${ideaId}`);
      const data = await res.json();
      setSelectedIdea(data);
    } catch (err) {
      console.error('Failed to fetch idea:', err);
    }
  };

  const formatTimeAgo = (date) => {
    const now = new Date();
    const then = new Date(date);
    const diffInHours = Math.floor((now - then) / (1000 * 60 * 60));
    
    if (diffInHours < 1) return 'Just now';
    if (diffInHours < 24) return `${diffInHours}h ago`;
    const diffInDays = Math.floor(diffInHours / 24);
    if (diffInDays < 7) return `${diffInDays}d ago`;
    return `${Math.floor(diffInDays / 7)}w ago`;
  };

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b-4 border-black py-6 px-4">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-4xl md:text-6xl font-black text-center">
            <span className="inline-block transform -rotate-1">ROAST</span>
            <span className="text-[#FF0055] inline-block transform rotate-1">MY</span>
            <span className="inline-block transform -rotate-1">IDEA</span>
          </h1>
        </div>
      </header>

      {/* Hero Section */}
      <section className="max-w-4xl mx-auto px-4 py-12 md:py-20">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-5xl font-black mb-4 leading-tight">
            GET YOUR STARTUP IDEA
            <br />
            <span className="text-[#FF0055]">BRUTALLY ROASTED</span>
          </h2>
          <p className="text-xl md:text-2xl text-gray-700 font-semibold">
            AI will roast your idea, then give you 10 real problems you'll face
            <br className="hidden md:block" />
            (and how to solve them)
          </p>
        </div>

        {/* Input Form */}
        <form onSubmit={handleSubmit} className="mb-12">
          <div className="mb-4">
            <textarea
              value={idea}
              onChange={(e) => setIdea(e.target.value)}
              placeholder="Describe your idea... (e.g., 'An app that uses AI to match you with the perfect houseplant based on your lifestyle')"
              className="w-full h-48 p-6 text-lg border-4 border-black focus:outline-none focus:ring-4 focus:ring-[#FF0055] resize-none"
              disabled={loading}
            />
            <div className="flex justify-between items-center mt-2">
              <span className={`text-sm font-semibold ${idea.length < 50 ? 'text-red-600' : idea.length > 2000 ? 'text-red-600' : 'text-gray-600'}`}>
                {idea.length} / 2000 characters {idea.length < 50 && '(min 50)'}
              </span>
            </div>
          </div>

          {error && (
            <div className="mb-4 p-4 bg-red-100 border-4 border-black">
              <p className="font-bold text-red-800 flex items-center gap-2">
                <X className="w-5 h-5" />
                {error}
              </p>
            </div>
          )}

          <button
            type="submit"
            disabled={loading || idea.length < 50 || idea.length > 2000}
            className="w-full bg-[#FF0055] text-white font-black text-xl py-6 brutalist-button disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <span className="flex items-center justify-center gap-2">
                <Flame className="w-6 h-6 animate-pulse" />
                ROASTING YOUR IDEA...
              </span>
            ) : (
              <span className="flex items-center justify-center gap-2">
                <Flame className="w-6 h-6" />
                ROAST MY IDEA
              </span>
            )}
          </button>
        </form>

        {/* Response Display */}
        {response && (
          <div className="space-y-8 animate-fadeIn">
            {/* The Roast */}
            <div className="border-4 border-black p-6 bg-white brutalist-shadow">
              <h3 className="text-2xl font-black mb-4 flex items-center gap-2">
                <Flame className="w-6 h-6 text-[#FF0055]" />
                THE ROAST
              </h3>
              <p className="text-lg leading-relaxed">{response.roast}</p>
            </div>

            {/* Problems & Solutions */}
            <div className="border-4 border-black p-6 bg-white brutalist-shadow">
              <h3 className="text-2xl font-black mb-6 flex items-center gap-2">
                <Flame className="w-6 h-6 text-[#FF0055]" />
                10 PROBLEMS YOU'LL ACTUALLY FACE
              </h3>
              <div className="space-y-6">
                {response.problems.map((item, index) => (
                  <div key={index} className="border-l-4 border-[#FF0055] pl-4">
                    <h4 className="font-black text-lg mb-2">
                      Problem #{index + 1}: {item.problem}
                    </h4>
                    <p className="text-gray-700 leading-relaxed">
                      <span className="font-bold">Solution:</span> {item.solution}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={copyToClipboard}
                className="flex-1 bg-black text-white font-bold text-lg py-4 brutalist-button flex items-center justify-center gap-2"
              >
                {copied ? (
                  <>
                    <Check className="w-5 h-5" />
                    COPIED!
                  </>
                ) : (
                  <>
                    <Copy className="w-5 h-5" />
                    COPY FULL RESPONSE
                  </>
                )}
              </button>
              <button
                onClick={shareRoast}
                className="flex-1 bg-[#FF0055] text-white font-bold text-lg py-4 brutalist-button flex items-center justify-center gap-2"
              >
                {shareCopied ? (
                  <>
                    <Check className="w-5 h-5" />
                    LINK COPIED!
                  </>
                ) : (
                  <>
                    <Share2 className="w-5 h-5" />
                    SHARE THIS ROAST
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </section>

      {/* Wall of Ideas */}
      <section className="bg-gray-50 border-t-4 border-black py-12 px-4">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-5xl font-black mb-8 text-center">
            <span className="text-[#FF0055]">WALL OF</span> IDEAS
          </h2>
          <p className="text-center text-xl font-semibold mb-12 text-gray-700">
            Ideas That Got Roasted
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {wallIdeas.map((item) => (
              <div
                key={item.id}
                onClick={() => openIdeaModal(item.id)}
                className="border-4 border-black p-6 bg-white brutalist-shadow cursor-pointer hover:transform hover:translate-x-1 hover:translate-y-1 transition-transform"
              >
                <p className="font-bold mb-2 line-clamp-3">{item.ideaSnippet}</p>
                <p className="text-gray-600 text-sm mb-4 line-clamp-2 italic">
                  "{item.roastSnippet}"
                </p>
                <p className="text-xs font-semibold text-[#FF0055]">
                  {formatTimeAgo(item.createdAt)}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Modal for viewing full idea */}
      {selectedIdea && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"
          onClick={() => setSelectedIdea(null)}
        >
          <div
            className="bg-white border-4 border-black max-w-4xl w-full max-h-[90vh] overflow-y-auto p-8 brutalist-shadow"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-start mb-6">
              <h3 className="text-2xl font-black">THE IDEA</h3>
              <button
                onClick={() => setSelectedIdea(null)}
                className="text-black hover:text-[#FF0055]"
              >
                <X className="w-8 h-8" />
              </button>
            </div>

            <p className="text-lg mb-8 leading-relaxed">{selectedIdea.idea}</p>

            <div className="border-t-4 border-black pt-6 mb-6">
              <h4 className="text-xl font-black mb-4 flex items-center gap-2">
                <Flame className="w-5 h-5 text-[#FF0055]" />
                THE ROAST
              </h4>
              <p className="text-lg leading-relaxed">{selectedIdea.roast}</p>
            </div>

            <div className="border-t-4 border-black pt-6">
              <h4 className="text-xl font-black mb-4">
                10 PROBLEMS & SOLUTIONS
              </h4>
              <div className="space-y-4">
                {selectedIdea.problems.map((item, index) => (
                  <div key={index} className="border-l-4 border-[#FF0055] pl-4">
                    <p className="font-bold mb-1">#{index + 1}: {item.problem}</p>
                    <p className="text-gray-700 text-sm">
                      <span className="font-semibold">Solution:</span> {item.solution}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="border-t-4 border-black py-8 px-4 bg-white">
        <div className="max-w-6xl mx-auto text-center">
          <p className="text-sm text-gray-600">
            The feedback provided is AI-generated and for entertainment purposes.
            <br />
            Always do your own research before building any product.
          </p>
          <p className="text-xs text-gray-500 mt-4">
            © 2025 RoastMyIdea.com - Built with 🔥 and brutal honesty
          </p>
        </div>
      </footer>
    </div>
  );
}