import { v4 as uuidv4 } from 'uuid';

export const mockIdeas = [
  {
    id: uuidv4(),
    idea_text: "An app that uses AI to match you with the perfect houseplant based on your lifestyle, space, and how often you forget to water things. It sends you reminders and care tips.",
    roast_text: "Oh great, another AI solution to a problem that literally didn't exist until someone decided plants needed algorithms. You know what also matches people with houseplants? Walking into a plant store and looking at the tags that say 'low maintenance' or 'needs daily watering.' But sure, let's throw machine learning at the age-old challenge of... reading. The best part? Your target market is people who can't keep a plant alive but somehow have the discipline to open an app every day. That's like making a gym membership app for people who hate exercise. At least when this fails, you can pivot to an AI that matches people with pet rocks - lower maintenance, higher survival rate.",
    problems: [
      { problem: "Market validation: The overlap between 'tech-savvy people who want plants' and 'people who need an app to care for plants' is microscopic.", solution: "Conduct 50+ user interviews with actual plant owners. Survey online plant communities to validate if they'd actually pay for this versus using free care guides." },
      { problem: "User acquisition: Plant enthusiasts already use Instagram, Reddit, and plant care blogs. You're competing with free, established communities.", solution: "Partner with plant influencers for co-marketing. Offer a freemium model with a genuinely useful free tier to drive adoption. Focus on one niche (e.g., office plants) first." },
      { problem: "Technical challenge: Accurate plant identification via photos requires extensive training data and is easily fooled by lighting/angles.", solution: "Start with manual plant selection instead of AI identification. Use Google's Vision API or Plant.id API for identification rather than building from scratch. Set expectations that AI isn't perfect." },
      { problem: "Monetization: Free plant care info is everywhere. Why would users pay?", solution: "Add value beyond info: personalized care schedules, local nursery discounts, plant health diagnostics. Consider B2B sales to nurseries/landscapers instead of consumer apps." },
      { problem: "Retention: Novelty wears off fast. After 2 weeks of reminders, users will ignore or uninstall.", solution: "Gamify the experience with plant growth tracking, community features (share plant pics), and achievements. Make the app a social experience, not just a notification system." },
      { problem: "Competition: There are already 20+ plant care apps. What makes yours different?", solution: "Research all competitors thoroughly. Find a specific underserved niche (e.g., rare plants, office environments, plant newbies only). Differentiate on UX or a unique feature." },
      { problem: "Technical challenge: Reliable reminder systems across iOS/Android with different notification policies is harder than it seems.", solution: "Use proven push notification services (Firebase, OneSignal). Test extensively on multiple devices. Have fallback in-app reminders and email options." },
      { problem: "Scaling: Supporting thousands of plant species with accurate care data requires constant maintenance and updates.", solution: "Start with top 100 most common houseplants. Build a community contribution system (Wikipedia-style) for expanding plant database. Partner with botanical gardens for expert validation." },
      { problem: "Business model: Ad-supported apps in niche categories barely generate revenue. Subscription fatigue is real.", solution: "Hybrid model: freemium app with affiliate revenue from plant sales, premium features for serious enthusiasts. Consider white-label licensing to nurseries." },
      { problem: "Market size: The addressable market of people who want plants AND need an app is limited, capping growth potential.", solution: "Expand target market to adjacent niches: gardening, urban farming, grow-your-own-food. Consider corporate clients (office plant maintenance). Look at international markets where indoor plants are trending." }
    ],
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    is_mock: true
  },
  {
    id: uuidv4(),
    idea_text: "A dating app where you can only see matches when you're physically at the gym. It encourages people to work out more while finding fit partners.",
    roast_text: "Ah yes, because nothing says 'romance' like being sweaty, exhausted, and self-conscious about your body while swiping through potential dates. You've brilliantly combined two activities that people already find stressful - dating AND working out - into one anxiety-inducing package. The genius here is assuming people want to be judged on their attractiveness while they're at their absolute worst: red-faced, breathing heavily, and desperately trying not to make eye contact. Plus, you're targeting the tiny Venn diagram overlap of people who go to the gym regularly but are somehow still single and desperate enough to date there. Your competition? Every other person at the gym who can just... talk to people. Revolutionary!",
    problems: [
      { problem: "Market validation: Most people go to the gym to work out, not date. You're solving for a need that doesn't exist for most users.", solution: "Survey 200+ gym-goers about their interest in gym-based dating. Validate if 'meeting fit people' is actually a pain point or just a nice-to-have." },
      { problem: "User experience: People look and feel their worst at the gym. This is the opposite of when they want to present themselves to potential dates.", solution: "Pivot concept: Allow profile setup anytime, but boost visibility/matches when at gym. Gamify fitness goals with partner accountability instead of gym-only access." },
      { problem: "Privacy concerns: Geolocation tracking at gyms raises serious privacy and safety issues, especially for women.", solution: "Implement strict privacy controls: opt-in location sharing only during gym hours, ability to hide/block users, no precise location data. Get security audit before launch." },
      { problem: "Gym partnerships: You'll need deals with gym chains. They may view this as creepy or bad for business.", solution: "Frame it as a retention tool for gyms. Pitch data showing social connections increase gym membership retention. Start with boutique fitness studios that are more marketing-forward." },
      { problem: "Limited session time: Average gym visit is 45-60 minutes. Tiny window to match, chat, and connect.", solution: "Enable messaging outside gym hours once matched. Use gym time for initial matching, then allow normal chat flow. Focus on quality matches over quantity." },
      { problem: "Competition: Standard dating apps already have fitness filters and 'active lifestyle' options without the gym requirement.", solution: "Differentiate with verified gym attendance (proof of active lifestyle, not just claims). Add fitness challenge features. Partner with fitness influencers for credibility." },
      { problem: "Technical challenge: Accurate geolocation that distinguishes between actual gym-goers and people parked outside is complex.", solution: "Use multi-factor verification: gym WiFi connection + geofence + Bluetooth beacons. Partner with gyms for WiFi-based verification. Start with select locations for testing." },
      { problem: "User acquisition: Convincing people to download YET ANOTHER dating app with extra restrictions is an uphill battle.", solution: "Launch in fitness-obsessed cities (LA, NYC, Miami). Partner with CrossFit gyms and fitness influencers. Offer premium gym perks (free month, discounts) for early adopters." },
      { problem: "Seasonality: Gym attendance drops in summer and spikes in January. Your user base will fluctuate wildly.", solution: "Expand to outdoor fitness locations (parks, running trails, yoga studios). Add home workout integration with video verification. Build features that work year-round." },
      { problem: "Monetization: Dating app economics are brutal. Paid features in a restricted-use app will struggle even more.", solution: "Focus on gym partnerships for B2B revenue. Offer premium features: see who checked you out, priority matching, workout plan integration. Consider fitness brand sponsorships." }
    ],
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    is_mock: true
  },
  {
    id: uuidv4(),
    idea_text: "A browser extension that automatically summarizes every YouTube video before you watch it, showing you if it's worth your time.",
    roast_text: "Congratulations, you've invented the YouTube description and comments section, but with extra steps! Nothing screams 'I value my time' quite like installing a browser extension to tell you if a 10-minute video is worth watching, which itself takes 30 seconds to generate, plus the time you spent reading the summary. Here's a wild thought: YouTube already has a progress bar you can scrub through, and comments where people timestamp the good parts. But sure, let's add AI to make something that's already solved feel more 'innovative.' The real genius move here is targeting people who are so busy they need AI to filter their procrastination content. 'Sorry boss, I can't start that report yet, my video summary extension is still loading.'",
    problems: [
      { problem: "Market validation: YouTube's built-in chapters, descriptions, and 2x speed already solve this for most users.", solution: "Interview 100+ YouTube power users. Identify specific pain points your tool solves better. Survey which video categories most need summarization (tutorials vs. entertainment)." },
      { problem: "Technical challenge: Accurate video transcription and summarization requires processing audio, which is expensive and sometimes inaccurate.", solution: "Use YouTube's existing captions/transcripts (free). Leverage GPT-4 or Claude for summarization. Implement caching for popular videos. Start with videos that already have captions." },
      { problem: "Monetization: Browser extensions have notoriously low willingness-to-pay. Users expect free tools.", solution: "Freemium model: 10 summaries/day free, unlimited for $3-5/month. Add premium features: custom summary lengths, save summaries, quality scores. Consider B2B for corporate learning." },
      { problem: "User acquisition: Browser extension discovery is terrible. You're competing with thousands of productivity tools.", solution: "Launch on Product Hunt and Hacker News. Target productivity YouTubers for reviews. Use Reddit communities (r/productivity). Leverage TikTok for viral demos." },
      { problem: "YouTube API costs: Processing millions of videos gets expensive quickly, especially with AI summarization.", solution: "Only summarize videos when requested (not proactively). Cache summaries for popular videos. Set rate limits per user. Start with sponsor tier that covers API costs." },
      { problem: "Competition: Several extensions already do this (Eightify, YouTube Summary with ChatGPT, etc.).", solution: "Research all competitors. Find gaps: better accuracy, faster speed, specific niches (educational content, tutorials). Differentiate on UX or price point." },
      { problem: "Content creator backlash: Creators may hate tools that discourage watching full videos (fewer ad views, lower engagement).", solution: "Reframe as 'discovery tool' that helps users find relevant content faster. Show data that summaries increase click-through. Partner with educational creators who value accessibility." },
      { problem: "Technical challenge: Videos without captions or in non-English languages require expensive audio transcription.", solution: "Start English-only with caption requirement. Add whisper API for transcription as premium feature. Partner with Deepgram or AssemblyAI for cheaper transcription." },
      { problem: "Retention: Novelty tools see 80% drop-off after first week. How do you keep users engaged?", solution: "Add daily value: saved summaries library, search across watched videos, personalized recommendations. Send weekly digests of trending summarized content. Build habit through consistency." },
      { problem: "Legal risks: YouTube's ToS may prohibit scraping or modifying their interface. Could get shut down.", solution: "Review YouTube's ToS thoroughly. Use official API only. Don't modify YouTube's interface, add separate panel. Get legal review before launch. Have backup plan for ToS changes." }
    ],
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    is_mock: true
  },
  {
    id: uuidv4(),
    idea_text: "An app that tracks which friends owe you money and automatically sends them payment reminders. It also shows a leaderboard of who pays back fastest.",
    roast_text: "Oh perfect, an app that turns friendship into a competitive debt collection agency! Nothing strengthens bonds quite like passive-aggressive automated reminders and public shaming via leaderboard. 'Hey Sarah, you're in LAST PLACE for paying back that $8 for coffee!' Your app single-handedly answers the question nobody asked: 'How can I make lending my friend $20 as awkward as a corporate performance review?' The beautiful irony is that anyone neurotic enough to track small debts with an app probably already has a spreadsheet, and anyone chill enough not to care won't download it. You're building a relationship terminator disguised as a fintech solution. At least Venmo had the sense to make it fun and social. This is just... accounting with extra resentment.",
    problems: [
      { problem: "Market validation: Most people either don't care enough about small debts to track them, or use Venmo/Splitwise already.", solution: "Survey 200+ people about their actual pain points with friend payments. Identify if problem is tracking, requesting, or something else. Test concept with 20 beta users first." },
      { problem: "User experience: Automated reminders and leaderboards will damage friendships. Your app could become relationship poison.", solution: "Remove leaderboard entirely or make it opt-in and friendly. Add gentle reminder options (customizable tone). Focus on making payments easier, not enforcement." },
      { problem: "Competition: Venmo, Splitwise, and Cash App already solve this with massive user bases and network effects.", solution: "Find a specific niche they don't serve well: roommate expenses, group trips, business networking events. Differentiate on UX or integrate with existing payment apps." },
      { problem: "Network effect problem: App only works if both parties have it. Getting critical mass is nearly impossible.", solution: "Allow one-way tracking (you track debts even if friend doesn't have app). Send reminders via SMS/email without requiring app. Integrate with Venmo/PayPal APIs." },
      { problem: "Monetization: This is a low-frequency use case. Hard to charge for occasional debt tracking.", solution: "Freemium model: free for personal use, charge for groups or businesses. Take small percentage of payments processed. Offer premium features like receipt scanning, split recommendations." },
      { problem: "Social dynamics: People avoid awkward conversations. Your app makes the awkwardness automated, not eliminated.", solution: "Focus on making requests friendly and context-aware. Add features that frame it positively: thank you messages, easy split suggestions. Make the UX delightful, not demanding." },
      { problem: "Technical challenge: Integrating with multiple payment platforms (Venmo, PayPal, Zelle, etc.) is complex.", solution: "Start with just tracking and manual payment confirmations. Add payment integrations gradually. Use Plaid API for bank connections. Partner with one payment provider initially." },
      { problem: "User acquisition: Convincing people to download an app about money and debts is a tough sell.", solution: "Launch around natural pain points: post-vacation group trips, roommate rent splitting, holiday shopping. Target college students and young professionals. Use TikTok for viral demos." },
      { problem: "Privacy concerns: Tracking who owes money could expose sensitive financial information or create awkward situations.", solution: "Private by default - only you see your tracking. Opt-in for sharing. Strong encryption. Clear privacy policy. Allow anonymous mode for tracking without names." },
      { problem: "Cultural sensitivity: Different cultures have different norms around money and friendship. What works in US may not globally.", solution: "Research cultural differences in money lending. Make features customizable (disable reminders, adjust tone). Start in one market before expanding. Hire cultural consultants for localization." }
    ],
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    is_mock: true
  },
  {
    id: uuidv4(),
    idea_text: "Smart mirror that only shows your reflection on good hair days. On bad days, it just shows inspirational quotes instead.",
    roast_text: "Finally, a product for people whose self-esteem is so fragile they need their furniture to gaslight them! 'Don't worry, you don't look terrible today, here's a quote about inner beauty instead!' This is peak Silicon Valley innovation: take a perfectly functional mirror that costs $20, add unnecessary AI that will definitely misjudge your hair, jack the price up to $500, and call it 'wellness tech.' The product roadmap basically writes itself: Step 1: Sell expensive mirrors. Step 2: Make people dependent on algorithmic validation of their appearance. Step 3: Subscription model for premium quotes? The best part is that anyone secure enough to appreciate inspirational quotes probably doesn't need a mirror to hide from them on bad hair days. But hey, Black Mirror called and they want their episode premise back.",
    problems: [
      { problem: "Market validation: This is a novelty product masquerading as utility. Will people actually pay $400+ for a mirror that sometimes doesn't work?", solution: "Build a functional prototype first. Test with 50+ users in their homes for 30 days. Measure if they actually find it useful or just funny. Survey willingness to pay." },
      { problem: "Technical challenge: 'Good hair day' is subjective and varies by style, ethnicity, personal preference. AI can't reliably judge this.", solution: "Let users define their own 'good hair' criteria. Use before/after comparisons over time. Implement user feedback loop to train personal preferences. Consider manual mode toggle." },
      { problem: "User experience: Not seeing your reflection when you need it (getting ready) defeats the purpose of a mirror entirely.", solution: "Always show reflection, but add overlay features: styling tips, product recommendations, weather-based advice. Make it an enhanced mirror, not a conditional one." },
      { problem: "Monetization: Smart mirrors are expensive to manufacture ($200+ cost). Need high margins or subscriptions.", solution: "Price at $400-600 with premium positioning. Add subscription for daily AI styling tips, virtual try-on features. Partner with beauty brands for affiliate revenue." },
      { problem: "Competition: Smart mirrors exist (HiMirror, etc.) with actual useful features. Your gimmick won't compete.", solution: "Pivot to genuine utility: skin analysis, makeup tutorials, lighting adjustment, virtual try-on. Add the 'confidence mode' as a fun feature, not the main selling point." },
      { problem: "Production costs: Smart mirrors require display, camera, processing, cloud backend. BOM alone is $150-250.", solution: "Start with tablet-based prototype (use existing hardware). Explore licensing software to existing smart mirror manufacturers. Consider app-only version using phone camera." },
      { problem: "User acquisition: Smart home products require retail presence or strong online brand. Startup mirrors don't sell themselves.", solution: "Launch via Kickstarter to validate demand and presell units. Partner with beauty influencers. Target high-end interior design market. Consider hotel/salon B2B sales first." },
      { problem: "Retention: After novelty wears off, it's just an expensive mirror with occasional quotes.", solution: "Continuous feature updates: new analysis modes, style trends, social sharing, beauty routine tracking. Build an app ecosystem around the mirror for ongoing engagement." },
      { problem: "Privacy concerns: A camera in your bathroom analyzing your appearance daily is a massive privacy red flag.", solution: "Local processing only (no cloud uploads). Physical camera cover. Clear privacy policy. Emphasize data never leaves device. Get security certification." },
      { problem: "Market size: The overlap of people who want smart mirrors AND believe in this specific feature is tiny.", solution: "Expand target: general smart mirror with multiple modes (fitness tracking, news, calendar). Make 'confidence mode' one feature among many. Target wellness-focused demographics." }
    ],
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    is_mock: true
  }
];